version: 2.1
#jobs:
 # build:
  #  macos:
   #   xcode: 13.4.1 # Specify the Xcode version 
    #steps:
     # - checkout
     # - run: pod install # Install CocoaPods dependencies
      #- run: 
       #   name: Build and run tests
       #   command: fastlane scan 
     # - sonarcloud/scan
     # - store_test_results:
     #     path: test_output
     # - store_artifacts:
      #    path: test_output
       #   destination: scan-output
jobs:
  build:
    docker:
      - image: "linux"
      #- image: cimg/base:2020.01
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

